# fly.toml app configuration file generated for ss-core on 2025-04-02T01:20:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ss-core'
primary_region = 'yyz'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
